okhv = "OKH-LOSHv1.0"
name = "Shredder"
repo = "https://github.com/clavelma/shredder_v2/tree/main/Content/Shredder"
release = "https://github.com/clavelma/shredder_v2"
license = "GPL-3.0"
licensor = "BIANCIOTTO Tom {tom.bianciotto@grenoble-inp.org}"
readme = "https://github.com/clavelma/shredder_v2#readme"
technology-readiness-level = "OTRL-2"
documentation-readiness-level = "ODRL-2"
function = "https://github.com/clavelma/shredder_v2/tree/main/Content/Shredder/2.%20Specification"
